"""
run_crossversion_compare_tribs6.py
===================================
Companion to run_crossversion_truth_sweep.py (old repo, tRIBS-Pima-Canyon).
Takes a folder of already-generated truth files -- <label>_Outlet.qout +
<label>_params.json pairs, exactly the format that script's
generate_truth() archives them in -- and, for each one: stages it, then
builds + runs + scores THIS repo's tRIBS (6.0.0) against it.

This is the half of the cross-version check that actually involves two
different tRIBS versions. The old-repo script's own comparison runs only
ever compare its tRIBS against itself (see the CORRECTION note in that
script's docstring, added 2026-09-24 after the first run confirmed this
the hard way -- both example truths scored a perfect PBIAS=0%/KGE=1.0
match there, which is what same-version self-consistency looks like, not
cross-version agreement). This script is where a real comparison happens:
the truth file was generated by the OLD tRIBS in the other repo; every run
here uses the NEW tRIBS (6.0.0) build. That version gap is the entire
point.

GETTING THE TRUTH FOLDER HERE
-------------------------------
No automated transfer between the two Codespaces is wired up -- that
would need to know how (or whether) they share a remote you can push/pull
between, which wasn't established as of this writing. Until/unless that
changes, get calibration_work/truths/ (or whichever subset of files you
want) from the old repo onto this one however you've been moving files
so far (download + upload, most likely), then point --truths_dir at
wherever you put it. Everything from there is automated.

Deliberately mirrors run_crossversion_truth_sweep.py's shape (same CLI
options, same output conventions) so the two are easy to use together --
but is NOT a copy-paste of that script's build logic. This one is adapted
from build_sensitivity_run_tribs6.py (this repo's own build function),
carrying forward every fix made earlier in this migration:
  - ../init_data/... paths, not ../smf_init_data/...
  - soil.create_soil_table_from_map(), not a soils.sdt read
  - No model.inputtime / model.outhydrofilename (confirmed nonexistent
    on pytRIBS 1.0.0's Model class)
  - model.update_solar_position(watershed_boundary) before
    write_input_file() -- required in this version, computed ONCE here
    (not per-run, unlike build_sensitivity_run_tribs6.py's single-run
    design) since a sweep calling this many times shouldn't re-read and
    re-dissolve SMF_voi.shp's 3398 polygons on every single build.
  - Scores via run_sensitivity_single_interp_tribs6.py, which already
    sniffs old-format (tab-delimited, no real header) vs. new-format
    (comma-delimited, real header) .qout files automatically -- exactly
    what makes reading an OLD-repo-generated truth file work correctly
    here without any further changes to that script.

CHANNEL CONDUCTIVITY
----------------------
Unlike the old repo, the OPTPERCOLATION fix HAS shipped here (confirmed
by Tracy, 2026-09-24) -- this is exactly the environment where enabling
it would eventually make sense. Not turned on in this version, though:
TRUTH_PARAM_KEYS stays at the same five keys as the old repo's script for
now, so results stay directly comparable between the two tools while this
capability is still new. Add "channelconductivity_mmhr" here (mirroring
model.optpercolation/channelconductivity in build_run() below) once
that's actually wanted, not before.

Usage (run from the lab/ directory):
    # One comparison run per truth in the folder
    python run_crossversion_compare_tribs6.py --truths_dir ../transferred_truths --mode single

    # Small LHS sweep around each truth instead of a single point
    python run_crossversion_compare_tribs6.py --truths_dir ../transferred_truths --mode small_lhs --n 30

Truth folder format (produced by run_crossversion_truth_sweep.py):
    <label>_Outlet.qout
    <label>_params.json    -- {"Ks_mult": ..., "f_RS_abs": ..., "kinemvelcoef": ...,
                                "flowexp": ..., "channelroughness": ...}

Output:
    calibration_work/03_comparisons/summary_tables/crossversion_results_tribs6.csv
        (one row per comparison run, tagged with truth_label + all truth params)
    calibration_work/03_comparisons/summary_tables/crossversion_FAILED_tribs6.csv
"""

import argparse
import json
import os
import shutil
import signal
import subprocess
import sys
import time
from pathlib import Path

import geopandas as gpd
import numpy as np
import pandas as pd

import build_sensitivity_run_tribs6 as builder
from pytRIBS.classes import Project, Soil, Land, Met, Model

# Same five keys as the old repo's script, deliberately -- see module
# docstring "CHANNEL CONDUCTIVITY" section for why this isn't extended yet.
TRUTH_PARAM_KEYS = [
    "Ks_mult", "f_RS_abs", "kinemvelcoef", "flowexp", "channelroughness",
]

# Same bounds as the old repo's LHS_PARAMS (run_lhs_synth_Ks_f_100.py /
# run_crossversion_truth_sweep.py) -- reused unchanged so small_lhs/full_lhs
# sweeps here are directly comparable to anything run on the old side.
LHS_PARAMS = {
    "Ks_mult":  {"lo": 3.0,   "hi": 11.0, "scale": "linear"},
    "f_RS_abs": {"lo": 0.003, "hi": 0.05, "scale": "log"},
}

# "70" reused deliberately from the old repo's script -- same conceptual
# category of work (cross-version comparison), recorded in this project's
# memory (ways-of-working.md) so both repos' use of it stays consistent.
CROSSVERSION_CATEGORY = "70_crossversion_compare"
SCORING_SCRIPT = "run_sensitivity_single_interp_tribs6.py"


# -----------------------------------------------------------------------
# WATERSHED BOUNDARY -- computed once in main() and passed in, not
# recomputed per build like build_sensitivity_run_tribs6.py does (that
# script only ever builds one run per invocation; this one may build many
# in a single sweep, and re-reading + re-dissolving SMF_voi.shp's 3398
# polygons on every one of them would be pure waste).
# -----------------------------------------------------------------------
def load_watershed_boundary():
    voi = gpd.read_file('../init_data/shapefiles/SMF_voi.shp')
    try:
        return voi.union_all()       # geopandas >=0.14
    except AttributeError:
        return voi.unary_union       # older geopandas


# -----------------------------------------------------------------------
# BUILD ONE RUN -- adapted from build_input_file() in
# build_sensitivity_run_tribs6.py: takes a full params dict (any subset
# of TRUTH_PARAM_KEYS; anything not given falls back to builder.BASELINE)
# and an explicit run_id, instead of build_input_file()'s single
# (param_name, value) sweep pattern -- same generalization the old repo's
# script applies to build_only().
# -----------------------------------------------------------------------
def build_run(params, run_id, calib_dir, script_dir, watershed_boundary):
    run_input_dir      = calib_dir / "01_run_inputs"  / CROSSVERSION_CATEGORY
    run_results_dir    = calib_dir / "02_results"     / CROSSVERSION_CATEGORY / run_id
    csv_export_dir     = calib_dir / "03_comparisons" / "csv_exports"
    plot_export_dir    = calib_dir / "03_comparisons" / "hydrograph_plots"
    summary_export_dir = calib_dir / "03_comparisons" / "summary_tables"
    log_dir             = calib_dir / "06_logs"

    for folder in [run_input_dir, run_results_dir, csv_export_dir,
                   plot_export_dir, summary_export_dir, log_dir]:
        folder.mkdir(parents=True, exist_ok=True)

    original_baseline = builder.BASELINE.copy()
    for key in TRUTH_PARAM_KEYS:
        if key in params:
            builder.BASELINE[key] = params[key]

    try:
        baseline = builder.BASELINE
        Ks_mult, f_RS_abs = baseline["Ks_mult"], baseline["f_RS_abs"]
        As_value, Au_value = baseline["As_value"], baseline["Au_value"]
        thetaS_mult, psiB_mult = baseline["thetaS_mult"], baseline["psiB_mult"]

        proj = Project(os.getcwd(), builder.LOCATION, builder.EPSG)

        landuse_ras = '../init_data/LandUse.asc'
        shutil.copy(landuse_ras, proj.directories['land'])
        landuse_ras = f"{proj.directories['land']}/{os.path.basename(landuse_ras)}"

        soil_ras = '../init_data/ADOT_SoilTypes.asc'
        shutil.copy(soil_ras, proj.directories['soil'])
        soil_ras = f"{proj.directories['soil']}/{os.path.basename(soil_ras)}"

        soil = Soil(meta=proj.meta)
        shutil.copy('../init_data/SOLUS_Bedrock_m.asc', proj.directories['soil'])
        soil.bedrockfile['value'] = f"{proj.directories['soil']}/SOLUS_Bedrock_m.asc"
        shutil.copy('../init_data/InitGW_95pct_mm.asc', proj.directories['soil'])
        soil.gwaterfile['value']  = f"{proj.directories['soil']}/InitGW_95pct_mm.asc"
        soil.soilmapname['value'] = soil_ras

        soil_table = soil.create_soil_table_from_map()

        for soil_cls in soil_table:
            soil_cls['As'] = As_value
            soil_cls['Au'] = Au_value
            soil_cls['ks'] = 0.7
            soil_cls['Cs'] = 1.4e6
            cid = str(soil_cls['ID'])
            if cid in builder.SOIL_PARAM_LOOKUP:
                soil_params = builder.SOIL_PARAM_LOOKUP[cid]
                soil_cls['Ks']     = soil_params['Ks'] * Ks_mult
                soil_cls['thetaR'] = soil_params['thetaR']
                soil_cls['m']      = soil_params['m']
                soil_cls['PsiB']   = soil_params['PsiB'] * psiB_mult
                soil_cls['n']      = soil_params['n']
                raw_thetaS = soil_params['thetaS'] * thetaS_mult
                soil_cls['thetaS'] = max(raw_thetaS, soil_params['thetaR'] + 0.01)
                soil_cls['f'] = f_RS_abs if cid == '1' else soil_params['f']
            else:
                print(f"  WARNING: Soil ID {cid} not in lookup; using fallback defaults.")
                soil_cls['Ks'] = 10.0; soil_cls['thetaS'] = 0.4; soil_cls['thetaR'] = 0.05
                soil_cls['m'] = 0.2; soil_cls['PsiB'] = -200; soil_cls['f'] = 0.001; soil_cls['n'] = 0.4

        working_soil_table = Path("data/model/soil/soil.sdt")
        soil.write_soil_table(soil_table, str(working_soil_table), textures=False)
        run_soil_path = run_input_dir / f"soils_{run_id}.sdt"
        shutil.copy(working_soil_table, run_soil_path)
        soil.soiltablename['value'] = os.path.relpath(run_soil_path, script_dir)
        soil.optsoiltype['value']   = 0

        land = Land(meta=proj.meta)
        land.landmapname['value']   = f"{proj.directories['land']}/LandUse.asc"
        land.landtablename['value'] = f"{proj.directories['land']}/land_use_params.ldt"
        landuse_list = []
        for lu_id, lp in builder.LAND_PARAM_LOOKUP.items():
            row = lp.copy(); row['ID'] = lu_id; row['a'] = -9999; row['b1'] = -9999
            landuse_list.append(row)
        land.write_landuse_table(landuse_list, land.landtablename['value'])

        met = Met(meta=proj.meta)
        met.hydrometbasename['value'] = builder.LOCATION
        met.hydrometstations['value'] = "../init_data/met/Master_Met.sdf"
        met.gaugestations['value']    = "../init_data/met/Master_Precip.sdf"

        model = Model(met=met, land=land, soil=soil, mesh=None, meta=proj.meta)
        model.parallelmode['value']  = 0
        model.optmeshinput['value']  = 1
        model.inputdatafile['value'] = "../init_data/mesh/SMF_mesh"
        model.optbedrock['value']    = 1
        model.optsnow['value']       = 0      # CRITICAL: must stay 0
        model.optlanduse['value']    = 0

        # optpercolation deliberately always baseline (0) here -- see
        # module docstring "CHANNEL CONDUCTIVITY" section.
        model.optpercolation['value']      = baseline["optpercolation"]
        model.channelconductivity['value'] = baseline["channelconductivity_mmhr"] / 3.6e6
        model.channelporosity['value']     = baseline["channelporosity"]

        model.kinemvelcoef['value']      = baseline["kinemvelcoef"]
        model.flowexp['value']           = baseline["flowexp"]
        model.channelroughness['value']  = baseline["channelroughness"]
        model.channelwidthcoeff['value'] = baseline["channelwidthcoeff"]

        model.startdate['value']   = builder.START_DATE
        model.runtime['value']     = builder.RUNTIME_HOURS
        model.rainintrvl['value']  = builder.RAIN_INTERVAL
        model.opintrvl['value']    = 0.0833
        model.spopintrvl['value']  = 1

        input_file_abs    = run_input_dir   / f"{run_id}.in"
        log_file_abs      = log_dir         / f"{run_id}.log"
        output_prefix_abs = run_results_dir / run_id

        input_file    = os.path.relpath(input_file_abs,    script_dir)
        log_file      = os.path.relpath(log_file_abs,      script_dir)
        output_prefix = os.path.relpath(output_prefix_abs, script_dir)

        model.outfilename['value'] = output_prefix

        model.write_node_file([1960, 1547, 3082], 'data/model/pnodes.dat')
        model.nodeoutputlist['value'] = 'data/model/pnodes.dat'
        model.write_node_file([3202], 'data/model/qnodes.dat')
        model.outletnodelist['value'] = 'data/model/qnodes.dat'

        model.update_solar_position(watershed_boundary)

        model.write_input_file(input_file)

        run_config = {
            "location":                  builder.LOCATION,
            "event_date":                builder.EVENT_DATE,
            "run_id":                    run_id,
            "run_category":              CROSSVERSION_CATEGORY,
            "start_date":                builder.START_DATE,
            "runtime_hours":             builder.RUNTIME_HOURS,
            "rain_interval_hours":       builder.RAIN_INTERVAL,
            "event_start":               builder.EVENT_START,
            "event_end":                 builder.EVENT_END,
            "Ks_mult":                   Ks_mult,
            "f_RS_abs":                  f_RS_abs,
            "As_value":                  As_value,
            "Au_value":                  Au_value,
            "optpercolation":            baseline["optpercolation"],
            "channelconductivity_mmhr":  baseline["channelconductivity_mmhr"],
            "channelporosity":           baseline["channelporosity"],
            "kinemvelcoef":              baseline["kinemvelcoef"],
            "flowexp":                   baseline["flowexp"],
            "channelroughness":          baseline["channelroughness"],
            "channelwidthcoeff":         baseline["channelwidthcoeff"],
            "input_file":                input_file,
            "log_file":                  log_file,
            "output_prefix":             output_prefix,
            "csv_export_dir":            os.path.relpath(csv_export_dir,     script_dir),
            "plot_export_dir":           os.path.relpath(plot_export_dir,    script_dir),
            "summary_export_dir":        os.path.relpath(summary_export_dir, script_dir),
            "swept_param":               "crossversion_compare_tribs6",
            "swept_value":               Ks_mult,
        }
        config_path = calib_dir / "current_run_config.json"
        config_path.write_text(json.dumps(run_config, indent=2))

    finally:
        builder.BASELINE = original_baseline

    return run_id, input_file, log_file, output_prefix, run_results_dir, summary_export_dir


# -----------------------------------------------------------------------
# RUN SCORED -- same timeout-safe subprocess pattern used throughout this
# migration (own process group, SIGKILL on timeout, scan for tRIBS's own
# failure warning even on a clean exit code).
# -----------------------------------------------------------------------
def run_scored(timeout_sec):
    proc = subprocess.Popen(
        [sys.executable, SCORING_SCRIPT],
        cwd=Path.cwd(),
        start_new_session=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        text=True,
    )
    t0 = time.time()
    try:
        stdout, _ = proc.communicate(timeout=timeout_sec)
        timed_out = False
    except subprocess.TimeoutExpired:
        try:
            os.killpg(os.getpgid(proc.pid), signal.SIGKILL)
        except ProcessLookupError:
            pass
        stdout, _ = proc.communicate()
        timed_out = True
    elapsed = time.time() - t0

    if stdout:
        print(stdout, end="" if stdout.endswith("\n") else "\n")

    tribs_warning = bool(stdout) and "WARNING: tRIBS may have failed" in stdout
    returncode    = None if timed_out else proc.returncode
    return returncode, elapsed, timed_out, tribs_warning


# -----------------------------------------------------------------------
# DISCOVER TRUTHS -- scan --truths_dir for <label>_params.json files
# (the label is the filename stem minus "_params"), confirm each has a
# matching <label>_Outlet.qout alongside it, load the params.
# -----------------------------------------------------------------------
def discover_truths(truths_dir):
    truths_dir = Path(truths_dir)
    if not truths_dir.exists():
        raise RuntimeError(f"--truths_dir does not exist: {truths_dir}")

    specs = []
    for params_path in sorted(truths_dir.glob("*_params.json")):
        label = params_path.name[:-len("_params.json")]
        qout_path = truths_dir / f"{label}_Outlet.qout"
        if not qout_path.exists():
            print(f"  WARNING: {params_path.name} has no matching "
                  f"{qout_path.name} -- skipping '{label}'.")
            continue
        params = json.loads(params_path.read_text())
        missing = [k for k in TRUTH_PARAM_KEYS if k not in params]
        if missing:
            print(f"  WARNING: {label}_params.json missing {missing} -- skipping.")
            continue
        specs.append({"label": label, "qout_path": qout_path, **params})

    if not specs:
        raise RuntimeError(f"No valid truth pairs found in {truths_dir}.")
    return specs


# -----------------------------------------------------------------------
# STAGE TRUTH -- same archive-then-copy pattern as the old repo's
# stage_truth(), adapted to source from the discovered truth's already-
# known qout_path rather than a local truths/ registry (there isn't one
# here -- the truths already exist as files, generated elsewhere).
# -----------------------------------------------------------------------
def stage_truth(qout_path, calib_dir):
    synth_dir   = calib_dir / "synth_truth"
    archive_dir = calib_dir / "synth_truth_archive"
    synth_dir.mkdir(parents=True, exist_ok=True)
    archive_dir.mkdir(parents=True, exist_ok=True)

    for existing in synth_dir.glob("*.qout"):
        dest = archive_dir / existing.name
        if dest.exists():
            dest = archive_dir / f"{existing.stem}_{int(time.time())}{existing.suffix}"
        shutil.move(str(existing), str(dest))

    shutil.copy(qout_path, synth_dir / qout_path.name)

    qout_files = list(synth_dir.glob("*.qout"))
    if len(qout_files) != 1:
        raise RuntimeError(
            f"Staging left {len(qout_files)} files in {synth_dir}, expected "
            f"exactly 1: {[f.name for f in qout_files]}."
        )
    print(f"  Staged: {qout_files[0].name} (active in synth_truth/)")


# -----------------------------------------------------------------------
# LHS SAMPLE GENERATION -- unchanged from the old repo's script.
# -----------------------------------------------------------------------
def generate_lhs_samples(n, params, seed=None):
    rng     = np.random.default_rng(seed)
    samples = {}
    for param, bounds in params.items():
        lo, hi = bounds["lo"], bounds["hi"]
        scale  = bounds.get("scale", "linear")
        if scale == "log":
            log_lo, log_hi = np.log10(lo), np.log10(hi)
            intervals  = np.linspace(log_lo, log_hi, n + 1)
            log_points = rng.uniform(intervals[:-1], intervals[1:])
            points     = 10 ** log_points
        else:
            intervals = np.linspace(lo, hi, n + 1)
            points    = rng.uniform(intervals[:-1], intervals[1:])
        rng.shuffle(points)
        samples[param] = points
    return pd.DataFrame(samples)


# -----------------------------------------------------------------------
# MAIN
# -----------------------------------------------------------------------
def main():
    parser = argparse.ArgumentParser(
        description="Stage transferred truth file(s) and run this repo's "
                    "(new tRIBS 6.0.0) build against each -- the actual "
                    "cross-version half of the check.")
    parser.add_argument("--truths_dir", type=str, required=True,
                        help="Folder containing <label>_Outlet.qout + <label>_params.json "
                             "pairs (the format run_crossversion_truth_sweep.py's "
                             "generate_truth() archives them in)")
    parser.add_argument("--mode", choices=["single", "small_lhs", "full_lhs"], default="single",
                        help="What runs against each staged truth (default: single)")
    parser.add_argument("--n", type=int, default=30,
                        help="Sweep sample count for small_lhs/full_lhs modes (ignored for single)")
    parser.add_argument("--seed", type=int, default=42,
                        help="Random seed for LHS sweep sampling")
    parser.add_argument("--timeout", type=int, default=300,
                        help="Per-run hard timeout in seconds (default: 300)")
    args = parser.parse_args()

    script_dir  = Path.cwd()
    calib_dir   = script_dir.parent / "calibration_work"  # sibling of lab/, not nested
    summary_dir = calib_dir / "03_comparisons" / "summary_tables"
    summary_dir.mkdir(parents=True, exist_ok=True)

    out_path        = summary_dir / "crossversion_results_tribs6.csv"
    failed_log_path = summary_dir / "crossversion_FAILED_tribs6.csv"

    truth_specs = discover_truths(args.truths_dir)

    print(f"\n{'='*70}")
    print(f"Cross-version comparison (NEW tRIBS 6.0.0) -- {len(truth_specs)} "
          f"transferred truth(s), mode={args.mode}")
    if args.mode != "single":
        print(f"  {args.n} samples per truth, seed={args.seed}")
    print(f"  Scoring via: {SCORING_SCRIPT}")
    print(f"{'='*70}\n")

    print("Loading watershed boundary (once, shared across all builds)...")
    watershed_boundary = load_watershed_boundary()

    results         = []
    failed_log_rows = []
    if out_path.exists():
        try:
            results = pd.read_csv(out_path).to_dict("records")
            print(f"  Loaded {len(results)} existing result row(s) from {out_path.name}")
        except Exception as e:
            print(f"  Warning: could not load existing results ({e}). Starting fresh.")

    for spec in truth_specs:
        label = spec["label"]
        truth_params = {k: spec[k] for k in TRUTH_PARAM_KEYS}

        print(f"\n--- Truth: {label} ---")
        stage_truth(spec["qout_path"], calib_dir)

        if args.mode == "single":
            sweep_points = [{"Ks_mult": truth_params["Ks_mult"], "f_RS_abs": truth_params["f_RS_abs"]}]
        else:
            samples = generate_lhs_samples(args.n, LHS_PARAMS, seed=args.seed)
            sweep_points = samples.to_dict("records")

        for j, point in enumerate(sweep_points):
            run_params = {**truth_params, **point}
            run_id = (f"{builder.LOCATION}_{builder.EVENT_DATE}_"
                      f"{CROSSVERSION_CATEGORY.split('_')[0]}_{label}_"
                      f"Ks{builder.value_to_label(run_params['Ks_mult'])}x_"
                      f"f{builder.value_to_label(run_params['f_RS_abs'])}")

            print(f"  [{j+1}/{len(sweep_points)}] {run_id}")
            t0 = time.time()
            try:
                (run_id, input_file, log_file, output_prefix,
                 run_results_dir, summary_export_dir) = build_run(
                    run_params, run_id, calib_dir, script_dir, watershed_boundary)
                returncode, elapsed, timed_out, tribs_warning = run_scored(args.timeout)

                if timed_out:
                    status = "HANG"
                elif returncode != 0 or tribs_warning:
                    status = "FAILED"
                else:
                    status = "SUCCESS"

                if status == "SUCCESS":
                    metrics_file = summary_export_dir / f"{run_id}_metrics_summary.csv"
                    metrics = pd.read_csv(metrics_file).iloc[0].to_dict()
                    metrics["truth_label"] = label
                    for k in TRUTH_PARAM_KEYS:
                        metrics[f"truth_{k}"] = truth_params[k]
                    results = [r for r in results if r.get("run_id") != run_id]
                    results.append(metrics)
                else:
                    reason = ("wall-clock timeout" if timed_out else
                              "tRIBS reported non-zero exit" if tribs_warning else
                              f"{SCORING_SCRIPT} exited {returncode}")
                    print(f"    {status}: {reason}")
                    failed_log_rows.append({
                        "run_id": run_id, "truth_label": label, "status": status,
                        "reason": reason, "elapsed_min": elapsed / 60,
                        **{f"truth_{k}": truth_params[k] for k in TRUTH_PARAM_KEYS},
                        **point,
                    })
                    pd.DataFrame(failed_log_rows).to_csv(failed_log_path, index=False)

            except Exception as e:
                print(f"    FAILED (build error): {e}")
                failed_log_rows.append({
                    "run_id": run_id, "truth_label": label, "status": "BUILD_ERROR",
                    "reason": str(e), "elapsed_min": (time.time() - t0) / 60,
                    **{f"truth_{k}": truth_params[k] for k in TRUTH_PARAM_KEYS},
                    **point,
                })
                pd.DataFrame(failed_log_rows).to_csv(failed_log_path, index=False)

            if results:
                pd.DataFrame(results).to_csv(out_path, index=False)

    print(f"\n{'='*70}")
    print(f"Done: {len(results)} result row(s), {len(failed_log_rows)} FAILED/HANG.")
    print(f"Saved: {out_path}")
    if failed_log_rows:
        print(f"Saved: {failed_log_path}")
    print(f"{'='*70}\n")


if __name__ == "__main__":
    main()
